# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LucsonAssignment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LucsonAssignment

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'IQKeyboardManagerSwift'
pod 'Alamofire'
pod 'ReachabilitySwift'
pod 'SVProgressHUD'

end
